# Generated by Django 6.0.7 on 2026-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription_libre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('effectif', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('valide', 'Validé')], default='en attente', max_length=20)),
            ],
        ),
    ]
